version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:20.5.0

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Notify Slack
          command: |
            curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ CircleCI build passed!"}' \
            $SLACK_WEBHOOK

workflows:
  version: 2
  test-and-notify:
    jobs:
      - test
